### ISSUE TITLE
Saved model after training?

### ISSUE THREAD

**Issue by CiaraG98** [huggingface/transfer-learning-conv-ai#104]
Where exactly is the model saved after executing train.py? I am training on a different laptop and want to run interact.py on my laptop with the model I trained on another laptop.

**Comment by gorkemgoknar** [comment]
Model is actually on the checkpoint itself (runs folder), you need to rename last checkpoint.pt to pytorch_model.bin then load model as in normal huggingface models (from_pretrained).  There seems to be a bug in last checkpoint rename.
