### ISSUE TITLE
Online demo is not available duo to CORS

### ISSUE THREAD

**Issue by imageslr** [huggingface/transfer-learning-conv-ai#105]
Access to fetch at 'https://convai-proxy.huggingface.co/messages/toto?text=123' from origin 'https://convai.huggingface.co' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by julien-c** [comment]
The demo's backend is offline unfortunately.

It should be reasonably easy to run the code in this repo on your side, but we have no short-term plan to start a server again on our side.

Sorry about that :/

**Comment by imageslr** [comment]
Thanks for your response. I have run the model on my server and it worked quit well :)

**Comment by imageslr** [comment]
By the way, is the demo's code public?
