### ISSUE TITLE
Running interact.py using GPT2 model has several problems

### ISSUE THREAD

**Issue by tomgun132** [huggingface/transfer-learning-conv-ai#16]
I tried to run interact.py using GPT2 model as it is and I faced several problems. My pytorch-pretrained-bert version is already the latest, which is 0.6.2. The problem that occurred:
1. There was unicode error when loading vocab.json from GPT2Tokenizer. I added utf-8 encoding to the open json file function and the problem is gone... hopefully
2. There was dimension mismatch when loading convai pretrained model's weight. I looked at the source code at the installed pytorch-pretrained-bert and compared it with the github repo and realized that in the installed version, modeling_gpt2.py doesn't have set_num_special_tokens function to add persona chat special tokens. I copied the modeling_gpt2.py from github to my installed folder and the problem is gone... hopefully as well
3. Decoded token has weird output:
```
INFO:interact.py:Selected personality: i<unk>prefer<unk>vinyl<unk>records<unk>to<unk>any<unk>other<unk>music<unk>recording<unk>format<unk>.i<unk>fix<unk>airplanes<unk>for<unk>a<unk>living<unk>.i<unk>drive<unk>junk<unk>cars<unk>that<unk>no<unk>one<unk>else<unk>wants<unk>.i<unk>think<unk>if<unk>i<unk>work<unk>hard<unk>enough<unk>i<unk>can<unk>fix<unk>the<unk>world<unk>.i<unk>am<unk>never<unk>still<unk>.
>>> k
Traceback (most recent call last):
  File "interact.py", line 146, in <module>
    run()
  File "interact.py", line 141, in run
    out_text = tokenizer.decode(out_ids, skip_special_tokens=True)
TypeError: decode() got an unexpected keyword argument 'skip_special_tokens'
```
Then I copied tokenization_gpt2 from pytorch-pretrained-bert master branch to my installed folder, then the result looks like this:
```
INFO:interact.py:Selected personality: iprefervinylrecordstoanyothermusicrecordingformat.ifixairplanesforaliving.idrivejunkcarsthatnooneelsewants.ithinkifiworkhardenoughicanfixtheworld.iamneverstill.
>>> test
amaranth</w>chowhungered</w>libibickerstaff</w>kingsley</w>syd</w>implacsoapy</w>arabella</w>dina</w>keaton</w>unstoppimplackingsley</w>unladylike</w>mirroring</w>implacimplacwondr
```

Did I set it up wrong for using GPT2 model?
If I use GPT model, the code works well.

**Comment by sshleifer** [comment]
This is fixed on master!
