### ISSUE TITLE
train from checkpoint

### ISSUE THREAD

**Issue by nikhiljaiswal** [huggingface/transfer-learning-conv-ai#20]
can anyone help, how to continue training from the checkpoint. after training for 2 epochs, I tried to load the checkpoint and resume training, but was unable to do so.

**Comment by sshleifer** [comment]
Sure! You're checkpoint should be in a directory called `runs/<date_when_you_trained>`. You can continue training by adding `--model_checkpoint `runs/<date_when_you_trained>` to your train command.
