### ISSUE TITLE
Update GPT-2 model from 355M to 774M

### ISSUE THREAD

**Issue by thewaifuai** [huggingface/transfer-learning-conv-ai#25]
12 hours ago, OpenAI [released](https://openai.com/blog/gpt-2-6-month-follow-up/) their GPT-2 774M pre-trained model through their [commit on GitHub](https://github.com/openai/gpt-2/commit/f35fa1d920e9d2d0690f66d03aa3f76b3c59230e). Can you please update this repository to use that model? It is more powerful than the current GPT-2 355M pre-trained model.

**Comment by GraphGrailAi** [comment]
@thewaifuai  so it was updated?

**Comment by thewaifuai** [comment]
> @thewaifuai so it was updated?

I don't know
