### ISSUE TITLE
Training without personas

### ISSUE THREAD

**Issue by JohannesTK** [huggingface/transfer-learning-conv-ai#3]
Thank you for open-sourcing and such a well-written code!

Because most of the conversational AI datasets are without personas, then how to train without personas?

Will setting the [persona](https://github.com/huggingface/transfer-learning-conv-ai/blob/master/train.py#L75) to an empty string do the job?

**Comment by misrasaurabh1** [comment]
@JohannesTK did you try training this without personas? Were you successful?

**Comment by nikhiljaiswal** [comment]
@JohannesTK , did you manage to train without persona?
