### ISSUE TITLE
Can you please support datasets without multiple choice and personality?

### ISSUE THREAD

**Issue by dimeldo** [huggingface/transfer-learning-conv-ai#34]
Hello,

You've done good work. But most datasets out there don't have multiple candidates or personalities. Can you please have an option to support this kind of datasets--datasets that only contain the history of the conversation? Thank you.

**Comment by sshleifer** [comment]
Could definitely try.
What would your preferred input format be? See [`example_entry.py` ](https://github.com/huggingface/transfer-learning-conv-ai/blob/master/example_entry.py)for the current format.

**Comment by dimeldo** [comment]
I think a popular format is a .txt file where each line corresponds to a single dialogue, within each turn is separated by some delimiter (either a tab-token '\t', end of token '</t>', etc...). 

For example (sorry for the very boring conversation):

```
Hey, how are you doing?</t>I'm good how about you?</t>Prety well, what's new?</t>Nothing much.
Hey! Sup?</t>Not much, you?</t>
```

**Comment by dimeldo** [comment]
Hello, @sshleifer. Can you please support this kind of data?

**Comment by sshleifer** [comment]
Unlikely. I think we might eventually support not passing persona, and you can pass `num_candidates=1`, but I don't see huge value in supporting different raw data formats, given how many different ones there are.

**Comment by dimeldo** [comment]
So, an example entry would look like this?

```
EXAMPLE_ENTRY = {
    "utterances": [
        {"candidates": [
            "I'm good how about you?"
        ],
        "history": [
            "Hey, how are you doing?"
        ]
        },
        {"candidates": [
            "Prety well, what's new?"],
         "history": [
            "Hey, how are you doing?",
            "I'm good how about you?"]
         },
        {"candidates": [
            "Nothing much."],
         "history": [
             "Hey, how are you doing?",
            "I'm good how about you?",
            "Prety well, what's new?"
            ]
         },
    ]
}
```

**Comment by dimeldo** [comment]
@sshleifer ?

**Comment by sshleifer** [comment]
LGTM

**Comment by dimeldo** [comment]
Okay 👍 Thanks!

**Comment by dimeldo** [comment]
I actually decided to go with changing this line:
`sequence = [[bos] + list(chain(*persona))] + history + [reply + ([eos] if with_eos else [])]`
 to:
`sequence = [[bos]] + history + [reply + ([eos] if with_eos else [])]`

And to make the following changes:
Deleting: `for _ in range(args.personality_permutations):` and other stuff related to pesona.

```
def get_data_loaders(args, tokenizer):
    """ Prepare the dataset for training and evaluation """
    personachat = get_dataset(tokenizer, args.dataset_path, args.dataset_cache)

    logger.info("Build inputs and labels")
    datasets = {"train": defaultdict(list), "valid": defaultdict(list)}
    for dataset_name, dataset in personachat.items():
        num_candidates = len(dataset[0]["utterances"][0]["candidates"])
        if args.num_candidates > 0 and dataset_name == 'train':
            num_candidates = min(args.num_candidates, num_candidates)
        for dialog in dataset:
            for utterance in dialog["utterances"]:
                history = utterance["history"][-(2*args.max_history+1):]
                for j, candidate in enumerate(utterance["candidates"][-num_candidates:]):
                    lm_labels = bool(j == num_candidates-1)
                    instance, _ = build_input_from_segments(history, candidate, tokenizer, lm_labels)
                    for input_name, input_array in instance.items():
                        datasets[dataset_name][input_name].append(input_array)
                datasets[dataset_name]["mc_labels"].append(num_candidates - 1)
                datasets[dataset_name]["n_candidates"] = num_candidates
```

Should that work?

**Comment by dimeldo** [comment]
After a lot of testing, it seems like when `num_candidates=1` is set and the actual size of the candidates list in the dataset is 1, there's an error relating to the size of tensors during the evaluation of the model (validation). Training is alright. @sshleifer

**Comment by dimeldo** [comment]
Closing, reporting problem at #40.

**Comment by coderkhaleesi** [comment]
Hey @dimeldo  Were you able to train it finally by passing empty personalities? Also, how did you resolve the num_candidates issue?
@sshleifer
