### ISSUE TITLE
Train own persona: mismatch with dataset paths

### ISSUE THREAD

**Issue by GraphGrailAi** [huggingface/transfer-learning-conv-ai#36]
I have a mismatch while training with own data.
How to reproduce:
1) I have create my own dataset with 1 persona: my.json with the following structure:
```

{
   "train":[
      {
    "personality": ["first sentence .", "second sentence .",
                    "third sentence .", "four  sentence ."],
    "utterances": [
        {"candidates": [
...................................
...................................
         }
    ]
}
]}
```
2. Passed this file to train: 

`mypc@mypc-tf:~/docs/LocalRepository/transfer-learning-conv-ai$ python  ./train.py --gradient_accumulation_steps=4 --lm_coef=2.0 --max_history=2 --n_epochs=1 --num_candidates=4 --personality_permutations=2 --train_batch_size=1 --valid_batch_size=1 --dataset_path="my.json"`

3. After training finished i got `runs` folder with following folders:
Oct05_00-22-19_mypc-tf_openai-gpt
Oct05_01-32-39_mypc-tf_openai-gpt
that is strange because there 2 folders, not one. actual model is located in Oct05_01-32-39_mypc-tf_openai-gpt

4. But, when i call interact it behaves the wrong way:
`python ./interact.py --model_checkpoint ./runs/Oct05_01-32-39_mypc-tf_openai-gpt/`

result is

INFO:/home/mypc/docs/LocalRepository/transfer-learning-conv-ai/utils.py:Gathered 18878 personalities

So, no my personality from my.json, only all original personalities.

My guess i made a mistake during train script, it somehow got cached original dataset, how to fix?

**Comment by sshleifer** [comment]
1) you have one training example?
2) try passing `--dataset_cache` or `--dataset_path` to `interact.py`

**Comment by GraphGrailAi** [comment]
>     1. you have one training example?
> 
>     2. try passing `--dataset_cache` or `--dataset_path` to `interact.py`

Here is full traceback:

```
python ./interact.py --model_checkpoint ./runs/Oct05_01-32-39_joo-tf_openai-gpt/ --dataset_path="my.json"
INFO:./interact.py:Namespace(dataset_cache='./dataset_cache', dataset_path='my.json', device='cuda', max_history=2, max_length=20, min_length=1, model='gpt', model_checkpoint='./runs/Oct05_01-32-39_joo-tf_openai-gpt/', no_sample=False, seed=42, temperature=0.7, top_k=0, top_p=0.9)
INFO:./interact.py:Get pretrained model and tokenizer
INFO:pytorch_transformers.tokenization_utils:Model name './runs/Oct05_01-32-39_joo-tf_openai-gpt/' not found in model shortcut name list (openai-gpt). Assuming './runs/Oct05_01-32-39_joo-tf_openai-gpt/' is a path or url to a directory containing tokenizer files.
INFO:pytorch_transformers.tokenization_utils:loading file ./runs/Oct05_01-32-39_joo-tf_openai-gpt/vocab.json
INFO:pytorch_transformers.tokenization_utils:loading file ./runs/Oct05_01-32-39_joo-tf_openai-gpt/merges.txt
INFO:pytorch_transformers.tokenization_utils:loading file ./runs/Oct05_01-32-39_joo-tf_openai-gpt/added_tokens.json
INFO:pytorch_transformers.tokenization_utils:loading file ./runs/Oct05_01-32-39_joo-tf_openai-gpt/special_tokens_map.json
INFO:pytorch_transformers.tokenization_utils:loading file ./runs/Oct05_01-32-39_joo-tf_openai-gpt/tokenizer_config.json
WARNING:pytorch_transformers.tokenization_openai:ftfy or spacy is not installed using BERT BasicTokenizer instead of SpaCy & ftfy.
INFO:pytorch_transformers.modeling_utils:loading configuration file ./runs/Oct05_01-32-39_joo-tf_openai-gpt/config.json
INFO:pytorch_transformers.modeling_utils:Model config {
  "afn": "gelu",
  "attn_pdrop": 0.1,
  "embd_pdrop": 0.1,
  "finetuning_task": null,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "n_ctx": 512,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 12,
  "n_positions": 512,
  "n_special": 0,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "predict_special_tokens": true,
  "pruned_heads": {},
  "resid_pdrop": 0.1,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "torchscript": false,
  "vocab_size": 40483
}

INFO:pytorch_transformers.modeling_utils:loading weights file ./runs/Oct05_01-32-39_joo-tf_openai-gpt/pytorch_model.bin
INFO:pytorch_transformers.modeling_utils:Weights from pretrained model not used in OpenAIGPTLMHeadModel: ['multiple_choice_head.summary.weight', 'multiple_choice_head.summary.bias']
INFO:pytorch_transformers.tokenization_utils:Assigning <bos> to the bos_token key of the tokenizer
INFO:pytorch_transformers.tokenization_utils:Assigning <eos> to the eos_token key of the tokenizer
INFO:pytorch_transformers.tokenization_utils:Assigning <pad> to the pad_token key of the tokenizer
INFO:pytorch_transformers.tokenization_utils:Assigning ('<speaker1>', '<speaker2>') to the additional_special_tokens key of the tokenizer
INFO:./interact.py:Sample a personality
INFO:/home/joo/Документы/LocalRepository/transfer-learning-conv-ai/utils.py:Load tokenized dataset from cache at ./dataset_cache_OpenAIGPTTokenizer
INFO:/home/joo/Документы/LocalRepository/transfer-learning-conv-ai/utils.py:Filter personalities
INFO:/home/joo/Документы/LocalRepository/transfer-learning-conv-ai/utils.py:Gathered 18878 personalities
INFO:./interact.py:Selected personality: i prefer vinyl records to any other music recording format. i fix airplanes for a living. i drive junk cars that no one else wants. i think if i work hard enough i can fix the world. i am never still.
>>> can you drive a car?
no i don't, i just fix planes to make sure i get where i want to go
>>> 
```

Result remains the same for both `--dataset_cache` and `--dataset_path`, interaction works, but it always run the same personality (i prefer vinyl records to any other music recording format ..... etc). And no any mention on my custom personality i set up in my.json.
So i am still sure i simply reproduced your results in this repo on my PC

**Comment by GraphGrailAi** [comment]
I am still curious, was not able to pass my dataset:
1) I added to original 200mb json my personality
2) trained once more with `--dataset_path ./my.json`
3) invoke interact.py with new checkpoint and path python ./interact.py --model_checkpoint ./runs/Oct08_18-22-53_joo-tf_openai-gpt/ --dataset_path ./my.json
and it reports `Gathered 18878 personalities` (but not 18879, with my own).
I changed the code in interact.py to choose my first perosnality this way

was:
`personality = random.choice(personalities)`

become:
`personality = personalities[0]`

and this first personality is not mine.

**Comment by GraphGrailAi** [comment]
Solved: hardcoded dataset path in utils.py, dont know why it doesnot load usual way

**Comment by monisha08041998** [comment]
> Solved: hardcoded dataset path in utils.py, dont know why it doesnot load usual way

have u solved this issue?
