### ISSUE TITLE
num of candidates and labels 

### ISSUE THREAD

**Issue by anandhperumal** [huggingface/transfer-learning-conv-ai#43]
What is number of candidates ? is it the number of person in the chat?
And what is the use of setting -1 for all the labels except the last reply? 
And in the cost function the ignore index = -1, therefore the loss will not be calculated for this labels.

```
 instance["lm_labels"] = [-1] * len(instance["input_ids"])
```

And where is the distractor in this code?

**Comment by rlouf** [comment]
Next time, so we can help you quicker, would you mind pointing precisely where the lines are located in the code? Even better, providing a link?

I'm not familiar with this code in particular, but the "-1" labels stand for the padding tokens which is why you are skipping them for the loss.

**Comment by anandhperumal** [comment]
Sorry about that.
[https://github.com/huggingface/transfer-learning-conv-ai/blob/master/train.py](url)

**Comment by anandhperumal** [comment]
@thomwolf can you please comment on this. 
what is the reason behind training each input having kind of two sub inputs:
one with input : persona + history + reply and labels :all  -1 (my question is on this part, how is this helpful)
and persona  + history + reply and labels = reply 
the above scenario is for num_candidates =2 
Thanks
