### ISSUE TITLE
Loading same personality every time

### ISSUE THREAD

**Issue by Abhinav43** [huggingface/transfer-learning-conv-ai#45]
I am running the interact.py and it's loading same personality again and again

"INFO:interact.py:Selected personality: i prefer vinyl records to any other music recording format. i fix airplanes for a living. i drive junk cars that no one else wants. i think if i work hard enough i can fix the world. i am never still."

How to select a random personality every time or between the conversation? 

Is the pre-trained model trained on only on one personality?

**Comment by sshleifer** [comment]
Good catch!
Two options:
1) send a pr that deletes the setting of `random.seed` in `interact.py`
2) pass a new `--seed` argument to `interact.py` when  you want a new personality (not how it should be, I acknowledge.)

**Comment by nihil0** [comment]
I just opened #47 to fix this.

**Comment by sshleifer** [comment]
Thanks @nihil0 !
