### ISSUE TITLE
preplexity value increase raise when the training epochs over 3

### ISSUE THREAD

**Issue by kangzhonghua** [huggingface/transfer-learning-conv-ai#50]
I have tested many times and PPL value up grow when epochs over 3. I have question,  number of training epochs 3 is the best? Please give us your advice.

![training](https://user-images.githubusercontent.com/12265127/71619485-91250a00-2bff-11ea-95f8-2df93e342b73.png)

**Comment by kangzhonghua** [comment]
![personachat_self_original](https://user-images.githubusercontent.com/12265127/71624791-5337de00-2c1f-11ea-9a6a-65c8e0b74c75.png)
personachat_self_original dataset

**Comment by sshleifer** [comment]
Seems like 3 epochs is good!

**Comment by kangzhonghua** [comment]
Think you for your reply!
