### ISSUE TITLE
using question generation in isolation README.md clarification

### ISSUE THREAD

**Issue by mooreniemi** [huggingface/transfer-learning-conv-ai#55]
I was curious to try using the question generation component. Based on the [overall README](https://github.com/huggingface/transfer-learning-conv-ai#pretrained-model), I might expect to be able to run interact.py without any arguments, but this doesn't work:

```
ERROR:pytorch_pretrained_bert.modeling_openai:Model name '' was not found in model name list (openai-gpt). We assumed '' was a path or url but couldn't find files pytorch_model.bin and config.json at this path or url.
Traceback (most recent call last):
  File "question-generation/interact.py", line 238, in <module>
    run()
  File "question-generation/interact.py", line 149, in run
    model.to(args.device)
AttributeError: 'NoneType' object has no attribute 'to'
```

That is ok, I downloaded a pretrained model myself from Google drive and tried interact.py again (`python3 question-generation/interact.py --model_checkpoint ~/Downloads/gpt2_corefs_question_generation/`). When I did so, I first hit the below issue:

```
  File "question-generation/interact.py", line 238, in <module>
    run()
  File "question-generation/interact.py", line 152, in run
    data = get_positional_dataset_from_file(tokenizer, args.filename)
  File "/Users/amooren/Code/squash-generation/question-generation/dataloader.py", line 81, in get_positional_dataset_from_file
    with open(file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/instances_dev.pkl'
```

Reading the overall README, I inferred that I needed to download instances_dev.pkl, and I found something closely named instances_dev.pickle and instances_coref_dev.pickle [here](https://drive.google.com/drive/folders/1FlVtPgyBiJIEOIecnNLH3cg0EbKkK0Z4). I assumed I'd need the coref labeled one, as the pretrained folder is named "gpt2_**corefs**_question_generation". But when I tried to use this, I hit the next issue:

```
Traceback (most recent call last):
  File "question-generation/interact.py", line 238, in <module>
    run()
  File "question-generation/interact.py", line 168, in run
    para_index = inst["para_index"]
KeyError: 'para_index'
```

Would you mind clarifying the steps to test out just this component? It would greatly speed up my efforts.

**Comment by sshleifer** [comment]
It looks to me like you have other code (e.g. `dataloader.py`) from another repository. We don't have any instances_dev.pkl or dataloader.py

**Comment by mooreniemi** [comment]
Oh no, my apologies! I opened this in the wrong repo, as [squash](https://github.com/martiansideofthemoon/squash-generation) links to this one. I'll close this here.

**Comment by Vivaswan13** [comment]
@mooreniemi I am also facing the same problem, did you find the solution?
