### ISSUE TITLE
Error in Docker build

### ISSUE THREAD

**Issue by SioKCronin** [huggingface/transfer-learning-conv-ai#66]
I'm getting the following error in `Step 11/13` of the Docker installation (using Docker version 19.03.8):

`The command '/bin/sh -c pip3 install -r /tmp/requirements.txt' returned a non-zero code: 137`

I'm running on MacOS with no GPUs. Are there system requirement assumptions for this installation?

**Comment by nbertagnolli** [comment]
Go in docker preferences and increase your default memory size : ).  Looks like the container was killed, whenever this happens to me upping the memory usually fixes it.  I'm building this container with 5GB of memory on OSX and it works. : )

**Comment by SioKCronin** [comment]
You're the best. Thanks for this suggestion! 

I had to clean up some space as well, but everything looks good now :)
