### ISSUE TITLE
Building docker fails

### ISSUE THREAD

**Issue by FBosler** [huggingface/transfer-learning-conv-ai#73]
Currently trying to build the docker image on my local MacBook Pro 16". Build works up until the point when torch (currently version 1.5) is supposed to be installed.

```
Collecting torch (from -r /tmp/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/13/70/54e9fb010fe1547bc4774716f11ececb81ae5b306c05f090f4461ee13205/torch-1.5.0-cp36-cp36m-manylinux1_x86_64.whl (752.0MB)
Killed
The command '/bin/sh -c pip3 install -r /tmp/requirements.txt' returned a non-zero code: 137
```

The above error rears its ugly head after roughly 3 minutes or so. Any ideas what's going on here?

**Comment by nbertagnolli** [comment]
Go in docker preferences and increase your default memory size : ). Looks like the container was killed, whenever this happens to me upping the memory usually fixes it. I'm building this container with 5GB of memory on OSX and it works. : )
