### ISSUE TITLE
Can not train with gpt2?

### ISSUE THREAD

**Issue by ginlee** [huggingface/transfer-learning-conv-ai#8]
Hi, I really like your project, but I tried to train with gpt2, it does not work. Will you release some instructions for gpt2? Thank you for your work

**Comment by thomwolf** [comment]
what exact error did you get?

**Comment by ginlee** [comment]
It looks the only parameter I should set is --model_checkpoint="gpt2", is that correct? Then I got an error that there is no set_num_special_tokens() method in modeling_gpt2, then I replaced it with set_tied(), but it still does not work. The error is 

`INFO:/home/yuli23/huggingface/test_origin/transfer-learning-conv-ai/utils.py:Tokenize and encode the dataset
INFO:train.py:Build inputs and labels
INFO:train.py:Pad inputs and convert to Tensor
INFO:train.py:Build train and validation dataloaders
INFO:train.py:Train dataset (Batch, Candidates, Seq length): torch.Size([131438, 2, 280])
INFO:train.py:Valid dataset (Batch, Candidates, Seq length): torch.Size([7801, 20, 184])
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    train()
  File "train.py", line 230, in train
    tb_logger = TensorboardLogger(log_dir=None)
  File "/home/yuli23/huggingface/testvenv/lib/python3.6/site-packages/ignite/contrib/handlers/tensorboard_logger.py", line 355, in __init__
    self.writer = SummaryWriter(log_dir=log_dir)
  File "/home/yuli23/huggingface/testvenv/lib/python3.6/site-packages/tensorboardX/writer.py", line 254, in __init__
    self._get_file_writer()
  File "/home/yuli23/huggingface/testvenv/lib/python3.6/site-packages/tensorboardX/writer.py", line 310, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir, **self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_dir'`

**Comment by ginlee** [comment]
If I want to train it with gpt2, I think the only parameter I should set is --model_checkpoint="gpt2", and first is there is no set_num_special_tokens method in modeling_gpt2, and I replaced it with set_tied() in train.py, but I got some type errors.

TypeError: __init__() got an unexpected keyword argument 'log_dir'

I did install all the requirements and I use pytorch = 0.4.1, thanks for your explanation.

**Comment by budzianowski** [comment]
I'm running into similar problem!

**Comment by thomwolf** [comment]
Oh yes you are right, gpt2 depend on a PR of pytorch-pretrained-bert (https://github.com/huggingface/pytorch-pretrained-BERT/pull/597) which is not merged and released yet. I have to finish cleaning up the test for it.

If you want to use it in the meantime you can install pytorch-pretrained-bert from source like this:
```bash
git clone https://github.com/huggingface/pytorch-pretrained-BERT.git
cd pytorch-pretrained-BERT
git checkout attention
pip install -e .
```

It should work

**Comment by budzianowski** [comment]
This problems occurs for both gpt2 and openai-gpt. I did checkout to attention branch but I'm still obtatining similar problem:(

**Comment by thomwolf** [comment]
What is your exact error?

**Comment by budzianowski** [comment]
> Traceback (most recent call last):
  File "./train.py", line 250, in <module>
    train()
  File "./train.py", line 229, in train
    tb_logger = TensorboardLogger(log_dir=None)
  File "/home/dial/pfb30/scripts/poly/env/lib/python3.5/site-packages/ignite/contrib/handlers/tensorboard_logger.py", line 355, in __init__
    self.writer = SummaryWriter(log_dir=log_dir)
  File "/home/dial/pfb30/scripts/poly/env/lib/python3.5/site-packages/tensorboardX/writer.py", line 254, in __init__
    self._get_file_writer()
  File "/home/dial/pfb30/scripts/poly/env/lib/python3.5/site-packages/tensorboardX/writer.py", line 310, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir, **self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_dir'

**Comment by thomwolf** [comment]
You should update to the latest version of pytorch ignite (this change to tensorboardX was included [here](https://github.com/pytorch/ignite/blob/58a8f40bc2a2870c402a44c194829e904fc1133e/ignite/contrib/handlers/tensorboard_logger.py#L408))

**Comment by martiansideofthemoon** [comment]
I'm unable to train with GPT-2 since the class defined [here](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/modeling_gpt2.py) misses the function `set_num_special_tokens`.

**Comment by g-karthik** [comment]
> You should update to the latest version of pytorch ignite (this change to tensorboardX was included [here](https://github.com/pytorch/ignite/blob/58a8f40bc2a2870c402a44c194829e904fc1133e/ignite/contrib/handlers/tensorboard_logger.py#L408))

I have the latest version of ignite (verified by trying to pip install it again on my Amazon Deep Learning AMI EC2 instance after doing `source activate pytorch_p36`). I still get the same error that @budzianowski is referring to.

**Comment by g-karthik** [comment]
Created an issue in the Ignite repo, it looks like we need to downgrade from tensorboardX 1.7 or install the latest ignite from master: https://github.com/pytorch/ignite/issues/534

**Comment by g-karthik** [comment]
@thomwolf in train.py, you'll have to change this line:

```
checkpoint_handler = ModelCheckpoint(tb_logger.writer.log_dir, 'checkpoint', save_interval=1, n_saved=3)
```

to

```
checkpoint_handler = ModelCheckpoint(tb_logger.writer.logdir, 'checkpoint', save_interval=1, n_saved=3)
```

This is because in the latest version of tensorboardX (not in PyPI, in GitHub master branch), they've renamed `log_dir` to `logdir`.

**Comment by budzianowski** [comment]
Thanks for help, now it's up and running for me talking nicely!

**Comment by g-karthik** [comment]
> Oh yes you are right, gpt2 depend on a PR of pytorch-pretrained-bert ([huggingface/pytorch-pretrained-BERT#597](https://github.com/huggingface/pytorch-pretrained-BERT/pull/597)) which is not merged and released yet. I have to finish cleaning up the test for it.
> 
> If you want to use it in the meantime you can install pytorch-pretrained-bert from source like this:
> 
> ```shell
> pip uninstall pytorch-pretrained-BERT
> git clone https://github.com/huggingface/pytorch-pretrained-BERT.git
> cd pytorch-pretrained-BERT
> git checkout attention
> pip install -e .
> ```
> 
> It should work

@thomwolf can you merge to master from the attention branch and release this if it hasn't already been done yet? Thanks!

**Comment by dalpo814** [comment]
pip install tensorboardX < 1.7 works!

**Comment by sshleifer** [comment]
Should be fixed on master!
