### ISSUE TITLE
How can I employ the pretrained model without downloading via script?

### ISSUE THREAD

**Issue by LeeJiangWei** [huggingface/transfer-learning-conv-ai#83]
Hello,
I know it seems to be kind of stupid question, but I just simply couldn't find how to apply the model. Due to the region restriction, I could not download the model via the script. Thank you.

**Comment by ochen1** [comment]
You could try using Google Colab to run this...

**Comment by LeeJiangWei** [comment]
> You could try using Google Colab to run this...

Thanks for advice. I'll have a try maybe next time.

**Comment by ochen1** [comment]
Consider closing this issue?
